### ISSUE TITLE
Action uses deprecated NodeJS version 12

### ISSUE THREAD

**Issue by rob-de-jong-alliander** [SAP/project-piper-action#128]
Using this action issues a warning about the usage of NodeJS 12 which is deprecated.
Could you bump the version to a more recent version?

Kind Regards,
Rob

**Comment by gregorwolf** [comment]
Hello SAP Project Piper Team,

is there any update on this issue? When will #129 be merged?

Best Regards
Gregor

**Comment by vfweiss** [comment]
Now getting forced to run on NodeJS 16.
`The following actions uses node12 which is deprecated and will be forced to run on node16: SAP/project-piper-action@master. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/`

Is there any plan to fix it on the Action itself?

**Comment by kstiehl** [comment]
I am not actively working on the project anymore but I'll give it a look today.

**Comment by fwilhe** [comment]
I'm sorry I don't have write permissions to this repo anymore. I think this project is unmaintained and I'd not recommend to use it in this state. Not sure if anyone is able/willing to take over maintenance for this repo.

**Comment by gregorwolf** [comment]
Hi @SebastianWolf-SAP,

can you give some guidance regarding the status of this repository?

**Comment by jliempt** [comment]
We have upgraded the Node version (https://github.com/SAP/project-piper-action/pull/140) in the meantime, but apart from that this repo is indeed unmaintained. Internal discussion is still ongoing.

**Comment by gregorwolf** [comment]
Hi @jliempt, any result of the discussions yet?

**Comment by dellagustin-sap** [comment]
Since the issue reported here was solved with #140, I created a new issue dedicated to clarifying the maintenance status of this repository and I'll close this issue.
