### ISSUE TITLE
Project Piper Action without using Jenkins

### ISSUE THREAD

**Issue by Pavithra-Upadhya** [SAP/project-piper-action#139]
Hi Team, 

We want to use the following scenario from Project Piper for our On-prem S/4 system: **Set up a Pipeline-Based ABAP Development and Testing Process Using Git-Enabled Change and Transport System**
GitHub Actions are to be used to trigger Unit Test for CDS Views and deployment to TST system. 
For this, we have configured the following action in our repo's **workflows/cicd.yml** file: 

**_- name: Project "Piper" Action
        uses: SAP/project-piper-action@1.0
        with:
            command: gctsExecuteABAPQualityChecks_**

**.pipeline/config.yml** is configured as below:

**_steps:
      gctsExecuteABAPQualityChecks:
    host: 'https://abap_server_host:port'
    client: '100'
    abapCredentialsId: 'user_id_to_login_to_ABAP_system'
    repository: 'name_of_local_git_repo'
    atcCheck: false
    scope: 'repository'_**

However, the documentation mentioned [here](https://www.project-piper.io/steps/gctsExecuteABAPQualityChecks/) requires Jenkins Server and Pipeline as a prerequisite. But in our company, we no longer use Jenkins for CI/CD and recommended to use GitHub actions only. 
Is there a way to use project-piper-action purely with Github Actions without Jenkins? Appreciate your response, as this will help us in deciding the way forward. 

Regards,
Pavithra

**Comment by fwilhe** [comment]
Hi @Pavithra-Upadhya 

I think there is a misunderstanding. You've linked a piper step docu which mentions Jenkins, this says nothing about this action. The action does not have anything to do with Jenkins.

That being said in the current state of this repo I would not recommend to use the action, but rather to [download the piper cli tool](https://www.project-piper.io/cli/) and use it directly. This action is nothing more than a wrapper around a simple

```
wget https://github.com/SAP/jenkins-library/releases/latest/download/piper
chmod +x ./piper
./piper yourPiperStep
```

Hope that helps.

Best,
Florian

**Comment by Pavithra-Upadhya** [comment]
Hi Florian,

Getting this error when trying to use piper step gctsExecuteABAPQualityChecks via GitHub Actions: 
fatal gctsExecuteABAPQualityChecks - failure in get objects - could not get repository objects: HTTP GET request to https://**_host:port_**/sap/bc/cts_abapvcs/repository/**_repo_name_**/objects?sap-client=**_xxx_** failed: Get "https://**_host:port_**/sap/bc/cts_abapvcs/repository/**_repo_name_**/objects?sap-client=**_xxx_**": dial tcp: lookup **_host_** on 127.0.0.53:53: no such host

Is there any other additional config to be done other than what is listed above (i.e., Pipeline Config & GitHub Action files)?

Regards,
Pavithra

**Comment by fwilhe** [comment]
Hi @Pavithra-Upadhya 

I can't help you with the `gctsExecuteABAPQualityChecks` step, I'm sorry. This is not the scope of the github action. The message reads like your host is not reachable from the github actions runner.

Anyway, for issues with any of the steps please open an issue here: https://github.com/SAP/jenkins-library/issues

**Comment by Pavithra-Upadhya** [comment]
Resolved after using a self-hosted runner to run the Piper steps via GitHub actions
