### ISSUE TITLE
How use this github action to build a gradle project?

### ISSUE THREAD

**Issue by JosephCen** [SAP/project-piper-action#156]
As title, I want to build a java repo which's build tool is 'gradle'.
Where can I find the document for this github action.

**Comment by fwilhe** [comment]
You can use the [gradleExecuteBuild](https://www.project-piper.io/steps/gradleExecuteBuild/) step. this action does nothing more than delegate to the project 'Piper' cli tool.

**Comment by JosephCen** [comment]
Thx.
