### ISSUE TITLE
An interval seems to be left running which delays node from exiting for 30 seconds

### ISSUE THREAD

**Issue by ajrussellsap** [SAP/project-piper-action#220]
When using the project-piper-action from a workflow on a GitHub Enterprise server, I consistently see a 30-second delay when node exits.  This has also been noted by colleagues working on completely different projects.  This issue seems to happen when no github.com token is specificed and, after some investigation I have tracked it down to being caused by this `fetch` statement:

https://github.com/SAP/project-piper-action/blob/main/src/fetch.ts#L11

The debug output from a workflow step shows that the delay happens after the step has finished doing everything:

![piper-delay](https://github.com/user-attachments/assets/90243230-1720-4d73-8364-fbbf48b56e57)

A trace of the action shows that there is something (possibly an interval) that runs every second for 30 seconds which prevents node from exiting:

![piper-trace](https://github.com/user-attachments/assets/6dda1de0-2905-4b85-989c-ffe5e1446cbf)

I wasn't able to determine the precise reason why this fetch command leaves something running every second for the next 30 seconds but I found that using a HEAD request prevented the issue from happening.  I have created a pull request for this:

https://github.com/SAP/project-piper-action/pull/219

I was not able to use my own fork of project-piper-action directly in my workflow - due to the policy of the GitHub Enterprise server - but I was able to create a workflow that patches the index.js file before it gets called and this fixes the problem.  I would be happy to share that workflow privately if it helps.

Anyway, I would very grateful if you could resolve this issue (with my PR or any other way that you see fit) as it is adds about 5 minutes to the run time of every workflow for me and quite a few colleagues.

Many thanks

Alex

**Comment by AnsgarLichter** [comment]
I also observed the long running times and this issue looks promising to speed up the execution times significantly.

**Comment by sapll** [comment]
Now that I have noticed this it is maddening. Steps will do their job in a second (as visible from the output) and then I see them idling until the ~30 second mark:
![slow-piper](https://github.com/user-attachments/assets/b9540d41-7bd7-4cee-9964-b11576fb21a1)

The screenshot shows the "init" stage. Every step using the piper action takes at least 30 seconds.

**Comment by jliempt** [comment]
This has now been solved with Alex's fix. Thanks a lot!
