### ISSUE TITLE
Release first version

### ISSUE THREAD

**Issue by fwilhe** [SAP/project-piper-action#4]
Depends on #2 

This will allow us to have the action in Github's marketplace

**Comment by CCFenner** [comment]
We should strive to have a **minimum number of releases** for this repository. This is just a wrapper for the tool and we should not double our release efforts but limit the releases here to actual changes on the **action** itself.

**Comment by fwilhe** [comment]
I'm not sure what effort you refer to. I'm a proponent of the "release early, release often" philosophy, and I do think that releases should use a fixed version of the binary. Why not have weekly releases here?

**Comment by CCFenner** [comment]
> Why not have weekly releases here?

Because there is no real code change. 

So, what about this: The action *requires* that the user decides for a `version` to use, but we also support `master`(piper_master from last release) and `latest`(last release).

**Comment by fwilhe** [comment]
@CCFenner when would you be comfortable with doing a release? I see that having not too many releases would be nice, still we should give us the freedom to have releases when the action improved. I would like to have a release soon-ish so we can bring the action into the marketplace.
