### ISSUE TITLE
XSA: deploy to our on-premise system - which dockerimage?

### ISSUE THREAD

**Issue by diraschk** [SAP/project-piper-action#71]
Hi experts,
I try to set the values of the config.yml  file for the "XSA" target. I've never used ppiper before, its my first try and would like to use it for our dev-pipeline.

But now I'm struggling with the right image. Which image should I use?

Configuration (.pipeline/config.yml)¶
steps:
  mtaBuild:
    buildTarget: 'XSA'
      dockerImage: '<**ID_OF_THE_DOCKER_IMAGE'** # for legal reasons no docker image is provided.

Thanks for your help!

**Comment by radsoulbeard** [comment]
Hi @diraschk ,

in that case you need to build your image on your own.
Please follow the  Readme in https://github.com/SAP/devops-docker-xs-cli

Best regards !
